# Makefile:  Main Makefile for Cosniwa  [OCTAVE PORT]
#
# platforms:  Linux, Mac
# (c) Jacek Pierzchlewski, 2017  jacek@pierzchlewski.com
# license: BSD-2-Clause.

# Compile cCosniwa Octave module
.PHONY: build
build:
	make -C cpp/ compile

# Clean cCosniwa directory
.PHONY: clean
clean:
	make -C cpp/ clean
