# Makefile:  Main Makefile for Cosniwa  [OCTAVE PORT - C++ Implementation]
#
# platforms:  Linux, Mac
# (c) Jacek Pierzchlewski, 2017  jacek@pierzchlewski.com
# license: BSD-2-Clause.

# Compile cCosniwa Octave module
.PHONY: compile
compile:
	./compile.sh

# Clean cCosniwa directory
.PHONY: clean
clean:
	rm -f *.o
	rm -f *.oct
